import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

const R = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
  variable: '--font-roboto'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${R.variable} antialiased`}>{children}</body>
    </html>
  )
}
